export const SEED_ROUTES = [
  // ── Original routes ──
  {
    from: 'Indas',
    to: 'Kolkata',
    fromBn: 'ইন্দাস',
    toBn: 'কলকাতা',
    distance: '120 km',
    estimatedTime: '3 hours',
    suggestedFareMin: 250,
    suggestedFareMax: 400,
  },
  {
    from: 'Bankura',
    to: 'Kolkata',
    fromBn: 'বাঁকুড়া',
    toBn: 'কলকাতা',
    distance: '230 km',
    estimatedTime: '5 hours',
    suggestedFareMin: 400,
    suggestedFareMax: 600,
  },
  {
    from: 'Bishnupur',
    to: 'Kolkata',
    fromBn: 'বিষ্ণুপুর',
    toBn: 'কলকাতা',
    distance: '200 km',
    estimatedTime: '4.5 hours',
    suggestedFareMin: 350,
    suggestedFareMax: 550,
  },
  {
    from: 'Durgapur',
    to: 'Kolkata',
    fromBn: 'দুর্গাপুর',
    toBn: 'কলকাতা',
    distance: '180 km',
    estimatedTime: '3.5 hours',
    suggestedFareMin: 300,
    suggestedFareMax: 500,
  },
  {
    from: 'Indas',
    to: 'Bankura',
    fromBn: 'ইন্দাস',
    toBn: 'বাঁকুড়া',
    distance: '45 km',
    estimatedTime: '1.5 hours',
    suggestedFareMin: 100,
    suggestedFareMax: 200,
  },
  {
    from: 'Bankura',
    to: 'Durgapur',
    fromBn: 'বাঁকুড়া',
    toBn: 'দুর্গাপুর',
    distance: '80 km',
    estimatedTime: '2 hours',
    suggestedFareMin: 150,
    suggestedFareMax: 250,
  },
  // ── New routes ──
  {
    from: 'Indas',
    to: 'Burdwan',
    fromBn: 'ইন্দাস',
    toBn: 'বর্ধমান',
    distance: '90 km',
    estimatedTime: '2.5 hours',
    suggestedFareMin: 150,
    suggestedFareMax: 280,
  },
  {
    from: 'Burdwan',
    to: 'Kolkata',
    fromBn: 'বর্ধমান',
    toBn: 'কলকাতা',
    distance: '100 km',
    estimatedTime: '2.5 hours',
    suggestedFareMin: 200,
    suggestedFareMax: 350,
  },
  {
    from: 'Asansol',
    to: 'Kolkata',
    fromBn: 'আসানসোল',
    toBn: 'কলকাতা',
    distance: '200 km',
    estimatedTime: '4 hours',
    suggestedFareMin: 350,
    suggestedFareMax: 550,
  },
  {
    from: 'Asansol',
    to: 'Durgapur',
    fromBn: 'আসানসোল',
    toBn: 'দুর্গাপুর',
    distance: '40 km',
    estimatedTime: '1 hour',
    suggestedFareMin: 80,
    suggestedFareMax: 150,
  },
  {
    from: 'Arambagh',
    to: 'Kolkata',
    fromBn: 'আরামবাগ',
    toBn: 'কলকাতা',
    distance: '100 km',
    estimatedTime: '2.5 hours',
    suggestedFareMin: 200,
    suggestedFareMax: 350,
  },
  {
    from: 'Arambagh',
    to: 'Karunamoyee',
    fromBn: 'আরামবাগ',
    toBn: 'করুণাময়ী',
    distance: '20 km',
    estimatedTime: '45 mins',
    suggestedFareMin: 60,
    suggestedFareMax: 120,
  },
  {
    from: 'Kotulpur',
    to: 'Kolkata',
    fromBn: 'কোতুলপুর',
    toBn: 'কলকাতা',
    distance: '130 km',
    estimatedTime: '3 hours',
    suggestedFareMin: 250,
    suggestedFareMax: 400,
  },
  {
    from: 'Kotulpur',
    to: 'Bankura',
    fromBn: 'কোতুলপুর',
    toBn: 'বাঁকুড়া',
    distance: '35 km',
    estimatedTime: '1 hour',
    suggestedFareMin: 80,
    suggestedFareMax: 150,
  },
  {
    from: 'Kotulpur',
    to: 'Bishnupur',
    fromBn: 'কোতুলপুর',
    toBn: 'বিষ্ণুপুর',
    distance: '25 km',
    estimatedTime: '45 mins',
    suggestedFareMin: 60,
    suggestedFareMax: 120,
  },
  {
    from: 'Burdwan',
    to: 'Durgapur',
    fromBn: 'বর্ধমান',
    toBn: 'দুর্গাপুর',
    distance: '50 km',
    estimatedTime: '1.5 hours',
    suggestedFareMin: 100,
    suggestedFareMax: 180,
  },
  {
    from: 'Burdwan',
    to: 'Asansol',
    fromBn: 'বর্ধমান',
    toBn: 'আসানসোল',
    distance: '60 km',
    estimatedTime: '1.5 hours',
    suggestedFareMin: 120,
    suggestedFareMax: 200,
  },
  {
    from: 'Karunamoyee',
    to: 'Kolkata',
    fromBn: 'করুণাময়ী',
    toBn: 'কলকাতা',
    distance: '15 km',
    estimatedTime: '45 mins',
    suggestedFareMin: 50,
    suggestedFareMax: 100,
  },
  {
    from: 'Indas',
    to: 'Arambagh',
    fromBn: 'ইন্দাস',
    toBn: 'আরামবাগ',
    distance: '30 km',
    estimatedTime: '1 hour',
    suggestedFareMin: 70,
    suggestedFareMax: 130,
  },
];
