export const SEED_ROUTES = [
  {
    from: 'Indus',
    to: 'Kolkata',
    fromBn: 'ইন্দাস',
    toBn: 'কলকাতা',
    distance: '120 km',
    estimatedTime: '3 hours',
    suggestedFareMin: 250,
    suggestedFareMax: 400,
  },
  {
    from: 'Bankura',
    to: 'Kolkata',
    fromBn: 'বাঁকুড়া',
    toBn: 'কলকাতা',
    distance: '230 km',
    estimatedTime: '5 hours',
    suggestedFareMin: 400,
    suggestedFareMax: 600,
  },
  {
    from: 'Bishnupur',
    to: 'Kolkata',
    fromBn: 'বিষ্ণুপুর',
    toBn: 'কলকাতা',
    distance: '200 km',
    estimatedTime: '4.5 hours',
    suggestedFareMin: 350,
    suggestedFareMax: 550,
  },
  {
    from: 'Durgapur',
    to: 'Kolkata',
    fromBn: 'দুর্গাপুর',
    toBn: 'কলকাতা',
    distance: '180 km',
    estimatedTime: '3.5 hours',
    suggestedFareMin: 300,
    suggestedFareMax: 500,
  },
  {
    from: 'Indus',
    to: 'Bankura',
    fromBn: 'ইন্দাস',
    toBn: 'বাঁকুড়া',
    distance: '45 km',
    estimatedTime: '1.5 hours',
    suggestedFareMin: 100,
    suggestedFareMax: 200,
  },
  {
    from: 'Bankura',
    to: 'Durgapur',
    fromBn: 'বাঁকুড়া',
    toBn: 'দুর্গাপুর',
    distance: '80 km',
    estimatedTime: '2 hours',
    suggestedFareMin: 150,
    suggestedFareMax: 250,
  },
];
